I added POM page for EditAccountProfile and I added 1 element to POM …
QA4Everyone3/group_maria pull request #10
Opened 2021-12-17 23:21 UTC by JuliaEde

…ViewProfilePage (the element takes the unordered list from hamburger menu, I am not sure if I should use get or wrap it in an async, because in order to get this element, the hamburger button has to be clicked)

About the new EditAccountProfile POM page: I added all elements from the Edit Account Page, the only problem that I have is this line - return super.open('/user/61a639262d347ec0559fe77d/edit'); I don't know how to get User Id, that's why I created the new element in the ViewProfile.page.js, because it has the link to User profile with the User ID

2021-12-17 23:41 UTC, ponomid commented on test/pageobjects/EditAccountProfileJuliaE.page.js
> +class EditAccountProfileJuliaEPage extends Page {
Should be empty line between first and second

2021-12-18 00:11 UTC, JuliaEde commented on test/pageobjects/EditAccountProfileJuliaE.page.js
> +class EditAccountProfileJuliaEPage extends Page {
Илья, а можно прямо на сайте редактировать код?

2021-12-18 00:12 UTC, JuliaEde commented on test/pageobjects/EditAccountProfileJuliaE.page.js
> +class EditAccountProfileJuliaEPage extends Page {
Или нужно через вебшторм?

2021-12-18 00:16 UTC, ponomid commented on test/pageobjects/EditAccountProfileJuliaE.page.js
> +class EditAccountProfileJuliaEPage extends Page {
> Илья, а можно прямо на сайте редактировать код?

Можно и здесь. Переходишь в File changed > Edit File

2021-12-18 05:57 UTC, JuliaEde commented on test/pageobjects/EditAccountProfileJuliaE.page.js
> +class EditAccountProfileJuliaEPage extends Page {
Кажется получилось отредактировать

2021-12-19 13:58 UTC, yuliahar requested changes

2021-12-19 13:58 UTC, yuliahar commented on test/pageobjects/EditAccountProfileJuliaE.page.js
> +    open() {
Please comment this method for now.

2021-12-19 13:58 UTC, yuliahar commented on test/pageobjects/EditAccountProfileJuliaE.page.js
> +class EditAccountProfileJuliaEPage extends Page {
Please rename this class to EditAccountProfilePage

2021-12-19 13:58 UTC, yuliahar commented on test/pageobjects/EditAccountProfileJuliaE.page.js
> +        return $("//button[@class='MuiButton-root MuiButton-outlined MuiButton-outlinedPrimary MuiButton-sizeMedium MuiButton-outlinedSizeMedium MuiButtonBase-root mt-5 mr-3 css-79xub']");
Please try to find a locator without so many CSS classes

2021-12-19 13:58 UTC, yuliahar commented on test/pageobjects/EditAccountProfileJuliaE.page.js
> +        return $("//span[@class='MuiButton-startIcon MuiButton-iconSizeMedium css-6xugel']");
Please try to find a locator with fewer amount CSS classes.

2021-12-19 13:58 UTC, yuliahar commented on test/pageobjects/ViewProfile.page.js
>      async profilePage () {
Please rename this method to goToProfilePage

2021-12-19 13:58 UTC, yuliahar commented on test/pageobjects/ViewProfile.page.js
>      async profilePage () {
Add comment open method for now.

2021-12-20 00:49 UTC, JuliaEde commented on test/pageobjects/EditAccountProfileJuliaE.page.js
> +class EditAccountProfileJuliaEPage extends Page {
Done, renamed

2021-12-20 00:49 UTC, JuliaEde commented on test/pageobjects/EditAccountProfileJuliaE.page.js
> +    open() {
Done, open method commented

2021-12-20 01:23 UTC, JuliaEde commented on test/pageobjects/EditAccountProfileJuliaE.page.js
> +        return $("//button[@class='MuiButton-root MuiButton-outlined MuiButton-outlinedPrimary MuiButton-sizeMedium MuiButton-outlinedSizeMedium MuiButtonBase-root mt-5 mr-3 css-79xub']");
Done, renamed

2021-12-20 01:23 UTC, JuliaEde commented on test/pageobjects/EditAccountProfileJuliaE.page.js
> +        return $("//span[@class='MuiButton-startIcon MuiButton-iconSizeMedium css-6xugel']");
Done

2021-12-21 01:16 UTC, merged