Add new test for Problem entity
QA4Everyone3/group_maria pull request #45
Opened 2021-12-31 06:10 UTC by ponomid

2022-01-02 22:12 UTC, JuliaEde reviewed
Looks good!

2022-01-03 05:36 UTC, ponomid commented
> Looks good!

Thanks, but you did not approve))

2022-01-04 11:02 UTC, yuliahar requested changes

2022-01-04 19:01 UTC, ponomid commented on test/ui/pageobjects/problem/ProblemCreate.page.js
> +        await this.appleCompanyOption.click();
Done. Thank you!

2022-01-04 21:11 UTC, yuliahar approved these changes

2022-01-04 21:50 UTC, merged