Added new tests, added new method for uiMethods.helper.js following Y…
QA4Everyone3/group_maria pull request #55
Opened 2022-01-07 03:59 UTC by JuliaEde

…ulia Har steps and copy pasted new method for ProfileEdit.page.js, added new element for ProfileEdit.page.js

2022-01-07 04:56 UTC, valdisone commented on test/helpers/uiMethods.helper.js
> +    let result = await element.setValue(value);
it's not necessary to create variable, it's used only one time

2022-01-07 05:09 UTC, JuliaEde commented on test/helpers/uiMethods.helper.js
> +    let result = await element.setValue(value);
Thank you for the update, should I remove return result? Then what will the function return?

2022-01-07 05:10 UTC, JuliaEde commented on test/helpers/uiMethods.helper.js
> +    let result = await element.setValue(value);
return value?

2022-01-07 05:18 UTC, valdisone commented on test/ui/specs/user/profileEditFirstNameBoundary.spec.js
> +        let length1Name = 'J';
you can use the randomString() method to generate the string (as yuliahar mentioned), it was created but not yet used

2022-01-07 05:18 UTC, valdisone commented on test/ui/pageobjects/user/ProfileEdit.page.js
> +            await clearAndFillField(await this.inputLastName, lastName);
extra line

2022-01-07 05:21 UTC, valdisone commented on test/helpers/uiMethods.helper.js
> +    let result = await element.setValue(value);
`return await element.setValue(value);`

2022-01-07 05:25 UTC, JuliaEde commented on test/helpers/uiMethods.helper.js
> +    let result = await element.setValue(value);
ох, вот так, окей, спасибо, я раньше не писала методы, довольно сложно, но интересно!

2022-01-07 05:31 UTC, JuliaEde commented on test/ui/specs/user/profileEditFirstNameBoundary.spec.js
> +        let length1Name = 'J';
I tried but it failed, I don't know how to use it. It worked until the last step and when I execute expect it failed always.

2022-01-07 05:33 UTC, JuliaEde commented on test/ui/pageobjects/user/ProfileEdit.page.js
> +            await clearAndFillField(await this.inputLastName, lastName);
if should start on the same line where the previous if finished? like so: } if () ?

2022-01-08 02:59 UTC, JuliaEde commented on test/ui/pageobjects/user/ProfileEdit.page.js
> +            await clearAndFillField(await this.inputLastName, lastName);
I removed extra lines

2022-01-08 03:00 UTC, JuliaEde commented on test/helpers/uiMethods.helper.js
> +    let result = await element.setValue(value);
Rewrote the method, please check

2022-01-08 03:01 UTC, yuliahar requested changes

2022-01-08 03:01 UTC, yuliahar commented on test/ui/specs/user/profileEditFirstNameBoundary.spec.js
> +        let length1Name = 'J';
Just remind, firstly import method
`const { randomString } = require('../../../helpers/uiMethods.helper');`
then you can 
`let length16Name = await randomString(16);`

2022-01-08 03:07 UTC, JuliaEde commented on test/ui/specs/user/profileEditFirstNameBoundary.spec.js
> +        let length1Name = 'J';
Yes, I had problems with using this method yesterday and Maria told me to use simple variables for now

2022-01-08 03:14 UTC, yuliahar commented on test/ui/specs/user/profileEditFirstNameBoundary.spec.js
> +        let length1Name = 'J';
Please try to use this method another shot. If it continues to fail, please remind me to demonstrate how to apply this method during our meeting.

2022-01-08 03:18 UTC, JuliaEde commented on test/ui/specs/user/profileEditFirstNameBoundary.spec.js
> +        let length1Name = 'J';
Thank you Yulia, I will try to use it, once you will approve the merge. I am confused about how to edit this file now, so many files have changed. I removed the element title from the Profile Edit page and xit -ed the test that was using it once, will fix it after a merge, thank you! Let me know if there's other things I have to edit in this PR

2022-01-08 03:19 UTC, JuliaEde commented on test/ui/pageobjects/user/ProfileEdit.page.js
> +    get pageTitle() {
Done, removed, xit -ed the it that was using this element, will change to navbar after merge

2022-01-08 03:20 UTC, JuliaEde commented on test/helpers/uiMethods.helper.js
> +    while(await element.getValue() !== '') {
Done

2022-01-08 03:21 UTC, yuliahar commented on test/ui/specs/user/profileEditFirstNameBoundary.spec.js
> +        let length1Name = 'J';
ok

2022-01-08 03:25 UTC, yuliahar requested changes

2022-01-08 03:25 UTC, yuliahar commented on test/helpers/uiMethods.helper.js
> +    await element.click();
Please delete this line and try this method without await element.click.

2022-01-08 03:25 UTC, yuliahar commented on test/ui/pageobjects/user/ProfileEdit.page.js
> +            await clearAndFillField(await this.inputLastName, lastName);
Please return lines back. There are different if-s, therefore they should start from a new line.

2022-01-08 03:34 UTC, JuliaEde commented on test/helpers/uiMethods.helper.js
> +    await element.click();
Done, deleted

2022-01-08 03:34 UTC, JuliaEde commented on test/ui/pageobjects/user/ProfileEdit.page.js
> +            await clearAndFillField(await this.inputLastName, lastName);
Done, returned them back

2022-01-08 03:40 UTC, yuliahar approved these changes

2022-01-08 03:42 UTC, merged