Profile view adding more tests
QA4Everyone3/group_maria pull request #57
Opened 2022-01-08 00:57 UTC by JuliaEde

2022-01-08 02:41 UTC, yuliahar requested changes

2022-01-08 02:41 UTC, yuliahar commented on test/ui/specs/user/profileView.spec.js
> +        await clearInputValue(ProfileEditPage.inputExternalLinkToProfileImage);
Please use here method fillAndSave() from ProfileEditPage.js

2022-01-08 02:41 UTC, yuliahar commented on test/ui/specs/user/profileView.spec.js
> +        await expect(ProfilePage.userInitials).toHaveText('MJ');
Please remind me to go through this test at our meeting.

2022-01-08 02:57 UTC, JuliaEde commented on test/ui/specs/user/profileView.spec.js
> +        await clearInputValue(ProfileEditPage.inputExternalLinkToProfileImage);
Thank you for the update, I cannot use it yet, because the new PR with updated method is still pending and not merged to master.

2022-01-08 02:57 UTC, JuliaEde commented on test/ui/specs/user/profileView.spec.js
> +        await expect(ProfilePage.userInitials).toHaveText('MJ');
Okay, I will!

2022-01-08 03:19 UTC, yuliahar commented on test/ui/specs/user/profileView.spec.js
> +        await clearInputValue(ProfileEditPage.inputExternalLinkToProfileImage);
Oh no. Sorry, I completely forgot about that. You did an excellent job!

2022-01-08 03:43 UTC, JuliaEde commented on test/ui/specs/user/profileView.spec.js
> +        await clearInputValue(ProfileEditPage.inputExternalLinkToProfileImage);
Thank you for your time!

2022-01-08 03:44 UTC, yuliahar commented on test/ui/specs/user/profileView.spec.js
> +        await expect(ProfilePage.userInitials).toHaveText('MJ');
🤝

2022-01-09 17:47 UTC, yuliahar approved these changes

2022-01-10 03:14 UTC, merged