login_logout_activation_restorePassword
QA4Everyone3/group_maria pull request #61
Opened 2022-01-10 03:57 UTC by PolinaTc

added new tests and selectors for login logout activation and restorePassword features

2022-01-10 22:00 UTC, yuliahar requested changes

2022-01-10 22:00 UTC, yuliahar commented on test/ui/specs/auth/activation.spec.js
> +    //BUG: Valid activation link is loaded forever
Please report this bug in Trello.

2022-01-10 22:00 UTC, yuliahar commented on test/ui/specs/auth/activation.spec.js
> +       const activationLinkId = await registerUser(email, password);
const activationLinkId = (await registerUser(email, password)).activationLinkId;
        await browser.url(process.env.BASE_URL+"/activate/" + activationLinkId );

2022-01-10 22:00 UTC, yuliahar commented on test/ui/specs/auth/activation.spec.js
> +       const activationLinkId = await registerUser(email, password);
Please delete console.log and use .activationLinkId without Object.values

2022-01-10 22:00 UTC, yuliahar commented on test/ui/specs/auth/login.spec.js
> +        await PublicationsPage.navBar.logout();
to speed up our tests ( to save 5 secs in running tests), you can use 
```
    afterEach(function () {
        browser.execute(function () {
            window.localStorage.clear();
        });
    });
```
instead of 
```await PublicationsPage.navBar.logout();```

2022-01-10 22:00 UTC, yuliahar commented on test/ui/specs/auth/login.spec.js
> +        console.log(await browser.getTitle()); // outputs: "WebdriverIO · Next-gen browser and mobile automation test framework for Node.js"
Please remove ```console.log(await browser.getTitle());```

If this tests starts to fail, add the following code:
```
        const newTitle = 'WebdriverIO · Next-gen browser and mobile automation test framework for Node.js';
        browser.waitUntil(async () => {
            const pageTitle = await browser.getTitle();
            return pageTitle == newTitle;
        });
```

2022-01-10 22:00 UTC, yuliahar commented on test/data/expected.json
> +    "pageUrl": "https://enduring.netlify.app/login",
Please remove pageUrl from here and see below one of the possible ways how to implement pageUrl verification.

2022-01-10 22:00 UTC, yuliahar commented on test/ui/specs/auth/logout.spec.js
> +        await PublicationsPage.navBar.btnHamburgerMenu.waitForDisplayed(3000);
Tests passed without specifying timeout in waitForDisplayed. Have your tests been failed without timeout = 3000?

2022-01-10 22:00 UTC, yuliahar commented on test/ui/specs/auth/logout.spec.js
> +        await LoginPage.inputEmail.waitForDisplayed(3000);
is timeout = 3000 required?

2022-01-10 22:00 UTC, yuliahar commented on test/ui/specs/auth/logout.spec.js
> +        console.log(`current url = ${currentUrl}`);
Please remove console.log. Thanks

2022-01-10 22:00 UTC, yuliahar commented on test/ui/specs/auth/logout.spec.js
> +        await expect(currentUrl).toEqual(expected.auth.pageUrl);
1. Add to LoginPage the following:
```
    path = '/login';

    get path() { return this.path; }
...
```
2. Then use it in logout.spec.js file:
```
        const currentUrl = await browser.getUrl();
        await expect(currentUrl).toEqual(process.env.BASE_URL + LoginPage.path);
```

2022-01-10 22:00 UTC, yuliahar commented on test/ui/specs/auth/logout.spec.js
> +        const expectedPage = await LoginPage.inputEmail;
Please rewrite these 2 code lines to:
```
        await expect(await LoginPage.inputEmail).toHaveText('');
```
Also please add expect for inputPassword.

2022-01-10 23:03 UTC, yuliahar commented on test/ui/specs/auth/logout.spec.js
> +        await expect(currentUrl).toEqual(expected.auth.pageUrl);
or expect(browser).toHaveUrlContaining(LoginPage.path)

2022-01-11 02:10 UTC, PolinaTc commented on test/ui/specs/auth/logout.spec.js
> +        await PublicationsPage.navBar.btnHamburgerMenu.waitForDisplayed(3000);
@yuliahar Yes, there are needed more time to load login page after logout. Removing any of these two waiters failed the test, even one of them ( That's why I remained them

2022-01-11 03:01 UTC, yuliahar approved these changes

2022-01-11 16:58 UTC, PolinaTc commented on test/ui/specs/auth/activation.spec.js
> +       const activationLinkId = await registerUser(email, password);
done

2022-01-11 16:59 UTC, merged