Added 3 tests for registration, 2 el for Signup.page.js, one async fo…
QA4Everyone3/group_maria pull request #65
Opened 2022-01-12 00:16 UTC by JuliaEde

…r Signup.page.js, one block for expected.json

2022-01-13 01:55 UTC, yuliahar requested changes

2022-01-13 01:55 UTC, yuliahar commented on test/ui/specs/auth/registration/registrationNegative.spec.js
> +        await expect(await SignupPage.userExistsErrorMessage(testEmailValid)).toBeExisting();
Please try to fail your test. 
```
await expect(await SignupPage.userExistsErrorMessage(testEmailValid)).not.toBeExisting();
```

2022-01-13 01:55 UTC, yuliahar commented on test/ui/specs/auth/registration/registrationNegative.spec.js
> +        await expect(await SignupPage.userExistsErrorMessage(testEmailValid)).toBeExisting();
and it's better to use .toBeDisplayed()

2022-01-13 01:55 UTC, yuliahar commented on test/ui/specs/auth/registration/registrationNegative.spec.js
> +const dotEnvPassword = process.env.USER_PASSWORD;
Put 4th and 5th lines into describe, please.

2022-01-13 01:55 UTC, yuliahar commented on test/ui/specs/auth/registration/registrationNegative.spec.js
> +    it('SISO - 2: Should show input validation errors disappering', async () => {
Please fix typo in word disappearing

2022-01-13 01:55 UTC, yuliahar commented on test/ui/specs/auth/registration/registrationNegative.spec.js
> +        await expect(await SignupPage.userExistsErrorMessage(alreadyRegisteredEmail)).toBeTruthy();
Please use method .toBeDisplayed() instead of .toBeTruthy() and try to fail this test.

2022-01-13 03:58 UTC, JuliaEde commented on test/ui/pageobjects/auth/Signup.page.js
> +
Done, line removed

2022-01-13 04:07 UTC, JuliaEde commented on test/ui/specs/auth/registration/registrationNegative.spec.js
> +//https://docs.google.com/spreadsheets/d/1Eg-BVQyju1YcKWL2vJYnRgLNliGOS7Vpn982QCOd1_s/edit#gid=2&range=14:14
Done, removed

2022-01-13 04:07 UTC, JuliaEde commented on test/ui/specs/auth/registration/registrationNegative.spec.js
> +const dotEnvPassword = process.env.USER_PASSWORD;
Done, put in describe

2022-01-13 04:08 UTC, JuliaEde commented on test/ui/specs/auth/registration/registrationNegative.spec.js
> +        await expect(await SignupPage.userExistsErrorMessage(testEmailValid)).toBeExisting();
I tried to fail, but I couldn't

2022-01-13 04:08 UTC, JuliaEde commented on test/ui/specs/auth/registration/registrationNegative.spec.js
> +    it('SISO - 2: Should show input validation errors disappering', async () => {
Done, fixed, thank you!

2022-01-13 04:09 UTC, JuliaEde commented on test/ui/specs/auth/registration/registrationNegative.spec.js
> +        await expect(await SignupPage.userExistsErrorMessage(alreadyRegisteredEmail)).toBeTruthy();
It does not fail

2022-01-13 04:10 UTC, JuliaEde commented on test/ui/specs/auth/registration/registrationNegative.spec.js
> +        await SignupPage.signup(testEmailValid, dotEnvPassword);
I will try create new method after merging, would it be okay?

2022-01-13 04:32 UTC, JuliaEde commented on test/ui/specs/auth/registration/registrationNegative.spec.js
> +        await expect(await SignupPage.userExistsErrorMessage(alreadyRegisteredEmail)).toBeTruthy();
Yulia, PR tests check failed in github actions, but not test related to the changes I've done. 
Test that failed is E2E test - create solution and I did registration test and profile view in other PR

2022-01-13 16:48 UTC, yuliahar approved these changes

2022-01-13 16:48 UTC, merged

2022-01-14 05:15 UTC, JuliaEde commented on test/ui/specs/auth/registration/registrationNegative.spec.js
> +        await SignupPage.signup(testEmailValid, dotEnvPassword);
did the method implementation